# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddock < Formula
  desc "Multi-Claude Code account manager. Auto-switch per directory."
  homepage "https://github.com/ojuan19/paddock"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.3/paddock_Darwin_amd64.tar.gz"
      sha256 "56d88866c473d03ae1738f355b6b220442f6b8d69cd91551f0f33a7cf15dfbce"

      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.3/paddock_Darwin_arm64.tar.gz"
      sha256 "88ce860ff6d94720b6de3d9d4b3a3323b8c8c70d89a19ef486e61132dcf79c49"

      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.3/paddock_Linux_amd64.tar.gz"
      sha256 "7be76c67f63de737b840ffa8cb3f309339719e7cf4731f4e8e74b93ae667bd52"
      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.3/paddock_Linux_arm64.tar.gz"
      sha256 "ffe7eee3f0905478d3c452e95295bb93aab5d14b8cd2c0a52326feded9b56dd2"
      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  test do
    system "#{bin}/paddock", "--version"
  end
end
