# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddock < Formula
  desc "Multi-Claude Code account manager. Auto-switch per directory."
  homepage "https://github.com/ojuan19/paddock"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.2/paddock_Darwin_amd64.tar.gz"
      sha256 "fb0657fa5c9b4c2b026d6be0dbb1872f6bd0aded64d867c7113a38bac8227e80"

      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.2/paddock_Darwin_arm64.tar.gz"
      sha256 "bfd1a78b1b56a88d4ef96f27768f840ef92e4651990f9c22958dfd759729ea9f"

      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.2/paddock_Linux_amd64.tar.gz"
      sha256 "d73106e3879237baa3d97879eda10fc105a66a0f20450f6c9d8c8e9de5f6e7f0"
      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.2/paddock_Linux_arm64.tar.gz"
      sha256 "3f7697f01d9e703677cdbaf13f65fa5e89bf30be1df433843aac5174cebb0342"
      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  test do
    system "#{bin}/paddock", "--version"
  end
end
