# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddock < Formula
  desc "Multi-Claude Code account manager. Auto-switch per directory."
  homepage "https://github.com/ojuan19/paddock"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.0/paddock_Darwin_amd64.tar.gz"
      sha256 "f7879089d890abaf00c98e52dcfae56bfa46f24dd70d164e8eed8931893035e4"

      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.0/paddock_Darwin_arm64.tar.gz"
      sha256 "c498286d4c35a9a940a7f8f4427db55a5245ef4ecb1a6ecd1759d95630c1d0e2"

      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.0/paddock_Linux_amd64.tar.gz"
      sha256 "970ef629ea606627a00d1dcf07f3414b551df8f7a9e350d474080a8201cc1a71"
      define_method(:install) do
        bin.install "paddock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojuan19/paddock/releases/download/v0.1.0/paddock_Linux_arm64.tar.gz"
      sha256 "ac6b6490a0639a15984206ba827ffb1771c8c7d44267b4ad9e9077389fced14f"
      define_method(:install) do
        bin.install "paddock"
      end
    end
  end

  test do
    system "#{bin}/paddock", "--version"
  end
end
